#!/bin/bash
# build-iso.sh - Build autoinstall ISO using xorriso in-place modification
# Run inside multipass VM: ./output/scripts/build-iso.sh
# Generated from build-iso.sh.tpl - do not edit directly
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_ISO="$SCRIPT_DIR/ubuntu-autoinstall.iso"

# Image settings from image.config.yaml
RELEASE="{{ image.release }}"
TYPE="{{ image.type }}"
ARCH="{{ image.arch }}"

echo "=== Installing dependencies ==="
sudo apt-get update -qq
sudo apt-get install -y -qq xorriso cloud-image-utils wget

echo "=== Querying latest Ubuntu ISO ==="
ISO_URL=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{url}\n")
ISO_NAME=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{filename}\n")

echo "=== Downloading Ubuntu ISO (if not cached) ==="
if [ ! -f "$HOME/$ISO_NAME" ]; then
    wget -q --show-progress "$ISO_URL" -O "$HOME/$ISO_NAME"
else
    echo "Using cached ISO: $ISO_NAME"
fi

echo "=== Copying ISO for modification ==="
cp "$HOME/$ISO_NAME" "$OUTPUT_ISO"

echo "=== Creating config directories ==="
mkdir -p "$HOME/nocloud_add" "$HOME/grub_mod"

# user-data is generated by `make autoinstall` in output/
cp "$SCRIPT_DIR/user-data" "$HOME/nocloud_add/"

# meta-data is minimal
cat > "$HOME/nocloud_add/meta-data" << 'EOF'
instance-id: autoinstall-001
EOF

echo "=== Creating GRUB config ==="
cat > "$HOME/grub_mod/grub.cfg" << 'GRUBEOF'
set timeout=5
set default=0
loadfont unicode
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Autoinstall Ubuntu Server" {
    set gfxpayload=keep
    linux /casper/vmlinuz autoinstall ds=nocloud\;s=/cdrom/nocloud/ consoleblank=0 ---
    initrd /casper/initrd
}

menuentry "Ubuntu Server (Manual Install)" {
    set gfxpayload=keep
    linux /casper/vmlinuz ---
    initrd /casper/initrd
}
GRUBEOF

echo "=== Modifying ISO in-place with xorriso ==="
xorriso -indev "$OUTPUT_ISO" \
    -outdev "$OUTPUT_ISO" \
    -boot_image any replay \
    -map "$HOME/nocloud_add" /nocloud \
    -map "$HOME/grub_mod/grub.cfg" /boot/grub/grub.cfg \
    -commit

echo "=== Verifying ISO ==="
xorriso -indev "$OUTPUT_ISO" -ls /nocloud 2>/dev/null || true

echo "=== ISO built successfully ==="
ls -lh "$OUTPUT_ISO"
