#!/bin/bash
# build-iso.sh - Build autoinstall ISO using xorriso in-place modification
# Run inside multipass VM: ./output/scripts/build-iso.sh
# Generated from build-iso.sh.tpl - do not edit directly
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_ISO="$SCRIPT_DIR/ubuntu-autoinstall.iso"

# Image settings from image.config.yaml
RELEASE="{{ image.release }}"
TYPE="{{ image.type }}"
ARCH="{{ image.arch }}"

echo "=== Installing dependencies ==="
sudo apt-get update -qq
sudo apt-get install -y -qq xorriso cloud-image-utils wget distro-info

echo "=== Querying latest Ubuntu ISO ==="
if [ "$TYPE" = "live-server" ]; then
    # Live-server ISOs are on releases.ubuntu.com, not cloud-images
    # ubuntu-cloudimg-query doesn't support live-server, so we query dynamically

    # Get base version from codename (e.g., noble -> 24.04)
    BASE_VERSION=$(ubuntu-distro-info --series="$RELEASE" -r 2>/dev/null | cut -d' ' -f1)
    if [ -z "$BASE_VERSION" ]; then
        # Assume RELEASE is already a version number
        BASE_VERSION="$RELEASE"
    fi

    # Find latest point release from releases.ubuntu.com
    VERSION=$(curl -sL "https://releases.ubuntu.com/" | grep -oE "href=\"${BASE_VERSION}(\.[0-9]+)?/\"" | sed 's/href="//;s/\/"$//' | sort -V | tail -1)
    if [ -z "$VERSION" ]; then
        VERSION="$BASE_VERSION"
    fi

    # Scrape actual ISO filename from directory listing
    ISO_NAME=$(curl -sL "https://releases.ubuntu.com/${VERSION}/" | grep -oE "href=\"[^\"]+live-server[^\"]+\.iso\"" | sed 's/href="//;s/"$//' | grep "$ARCH" | head -1)
    if [ -z "$ISO_NAME" ]; then
        echo "ERROR: Could not find live-server ISO for ${VERSION} ${ARCH}"
        exit 1
    fi
    ISO_URL="https://releases.ubuntu.com/${VERSION}/${ISO_NAME}"
else
    # Use ubuntu-cloudimg-query for cloud images
    ISO_URL=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{url}\n")
    ISO_NAME=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{filename}\n")
fi
echo "ISO URL: $ISO_URL"

echo "=== Downloading Ubuntu ISO ==="
wget -q --show-progress "$ISO_URL" -O "$HOME/$ISO_NAME"
echo "Downloaded: $(ls -lh "$HOME/$ISO_NAME" | awk '{print $5}')"

echo "=== Creating config directories ==="
mkdir -p "$HOME/nocloud_add" "$HOME/grub_mod"

# user-data is generated by `make autoinstall` in output/
cp "$SCRIPT_DIR/user-data" "$HOME/nocloud_add/"

# meta-data is minimal
cat > "$HOME/nocloud_add/meta-data" << 'EOF'
instance-id: autoinstall-001
EOF

echo "=== Creating GRUB config ==="
cat > "$HOME/grub_mod/grub.cfg" << 'GRUBEOF'
set timeout=5
set default=0
loadfont unicode
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Autoinstall Ubuntu Server" {
    set gfxpayload=keep
    linux /casper/vmlinuz autoinstall ds=nocloud\;s=/cdrom/nocloud/ consoleblank=0 ---
    initrd /casper/initrd
}

menuentry "Ubuntu Server (Manual Install)" {
    set gfxpayload=keep
    linux /casper/vmlinuz ---
    initrd /casper/initrd
}
GRUBEOF

echo "=== Modifying ISO in-place with xorriso ==="
xorriso -indev "$OUTPUT_ISO" \
    -outdev "$OUTPUT_ISO" \
    -boot_image any replay \
    -map "$HOME/nocloud_add" /nocloud \
    -map "$HOME/grub_mod/grub.cfg" /boot/grub/grub.cfg \
    -commit

echo "=== Verifying ISO ==="
xorriso -indev "$OUTPUT_ISO" -ls /nocloud 2>/dev/null || true

echo "=== ISO built successfully ==="
ls -lh "$OUTPUT_ISO"
