#!/bin/bash
# build-iso.sh - Build autoinstall ISO using xorriso in-place modification
# Run inside multipass VM: ./output/scripts/build-iso.sh
# Generated from build-iso.sh.tpl - do not edit directly
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORK_ISO="$HOME/ubuntu-autoinstall.iso"

# Image settings from image.config.yaml
RELEASE="{{ image.release }}"
TYPE="{{ image.type }}"
ARCH="{{ image.arch }}"

echo "=== Installing dependencies ==="
sudo apt-get update -qq
sudo apt-get install -y -qq xorriso cloud-image-utils wget distro-info

echo "=== Querying latest Ubuntu ISO ==="
if [ "$TYPE" = "live-server" ]; then
    # Live-server ISOs are on releases.ubuntu.com, not cloud-images
    # ubuntu-cloudimg-query doesn't support live-server, so we query dynamically

    # Get base version from codename (e.g., noble -> 24.04)
    BASE_VERSION=$(ubuntu-distro-info --series="$RELEASE" -r 2>/dev/null | cut -d' ' -f1)
    if [ -z "$BASE_VERSION" ]; then
        # Assume RELEASE is already a version number
        BASE_VERSION="$RELEASE"
    fi

    # Find latest point release from releases.ubuntu.com
    VERSION=$(curl -sL "https://releases.ubuntu.com/" | grep -oE "href=\"${BASE_VERSION}(\.[0-9]+)?/\"" | sed 's/href="//;s/\/"$//' | sort -V | tail -1)
    if [ -z "$VERSION" ]; then
        VERSION="$BASE_VERSION"
    fi

    # Scrape actual ISO filename from directory listing
    ISO_NAME=$(curl -sL "https://releases.ubuntu.com/${VERSION}/" | grep -oE "href=\"[^\"]+live-server[^\"]+\.iso\"" | sed 's/href="//;s/"$//' | grep "$ARCH" | head -1)
    if [ -z "$ISO_NAME" ]; then
        echo "ERROR: Could not find live-server ISO for ${VERSION} ${ARCH}"
        exit 1
    fi
    ISO_URL="https://releases.ubuntu.com/${VERSION}/${ISO_NAME}"
else
    # Use ubuntu-cloudimg-query for cloud images
    ISO_URL=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{url}\n")
    ISO_NAME=$(ubuntu-cloudimg-query "$RELEASE" "$TYPE" "$ARCH" --format "%{filename}\n")
fi
echo "ISO URL: $ISO_URL"

echo "=== Downloading Ubuntu ISO ==="
wget -q --show-progress "$ISO_URL" -O "$HOME/$ISO_NAME"
echo "Downloaded: $(ls -lh "$HOME/$ISO_NAME" | awk '{print $5}')"

echo "=== Creating GRUB config ==="
mkdir -p "$HOME/grub_mod"
# Note: autoinstall keyword triggers autoinstall
# ds=nocloud tells cloud-init to look for nocloud datasource (CIDATA labeled disk)
cat > "$HOME/grub_mod/grub.cfg" << 'GRUBEOF'
set timeout=5
set default=0
loadfont unicode
set menu_color_normal=white/black
set menu_color_highlight=black/light-gray

menuentry "Autoinstall Ubuntu Server" {
    set gfxpayload=keep
    linux /casper/vmlinuz quiet autoinstall ---
    initrd /casper/initrd
}

menuentry "Ubuntu Server (Manual Install)" {
    set gfxpayload=keep
    linux /casper/vmlinuz ---
    initrd /casper/initrd
}
GRUBEOF

echo "=== Creating CIDATA ISO ==="
# Ubuntu 24.04 requires a separate disk labeled CIDATA for cloud-init nocloud datasource
# Use cloud-localds which properly creates nocloud-compatible seed ISO
CIDATA_ISO="$HOME/cidata.iso"

# Create meta-data for cloud-localds
META_DATA=$(mktemp)
echo "instance-id: autoinstall-001" > "$META_DATA"

# cloud-localds creates proper nocloud seed with correct format
# user-data is generated by `make autoinstall` in output/
cloud-localds "$CIDATA_ISO" "$SCRIPT_DIR/user-data" "$META_DATA"
rm -f "$META_DATA"

echo "CIDATA ISO created: $CIDATA_ISO"
ls -lh "$CIDATA_ISO"

echo "=== Creating modified ISO with xorriso ==="
# Remove any previous work file
rm -f "$WORK_ISO"

# Verify source ISO exists and has content
echo "Source ISO: $HOME/$ISO_NAME"
ls -lh "$HOME/$ISO_NAME"

# Copy source ISO to work location for in-place modification
# This preserves all boot structures better than creating a new ISO
cp "$HOME/$ISO_NAME" "$WORK_ISO"

# Use xorriso to modify ISO in-place
# -dev opens for modification
# -boot_image any keep preserves existing boot configuration
# -update replaces files while preserving ISO structure
# Update grub.cfg in both BIOS and EFI paths for universal boot support
xorriso -dev "$WORK_ISO" \
    -boot_image any keep \
    -update "$HOME/grub_mod/grub.cfg" /boot/grub/grub.cfg \
    -update "$HOME/grub_mod/grub.cfg" /EFI/boot/grub.cfg \
    -commit

echo "Output ISO:"
ls -lh "$WORK_ISO"

echo "=== Copying outputs ==="
cp "$CIDATA_ISO" "$SCRIPT_DIR/cidata.iso"
echo "$WORK_ISO" > "$SCRIPT_DIR/iso-location.txt"

echo "=== Build complete ==="
echo "CIDATA: $SCRIPT_DIR/cidata.iso"
echo "ISO: $WORK_ISO (use 'multipass transfer iso-builder:$WORK_ISO <dest>')"
