param([Parameter(Mandatory = $true)] $SDK)

New-Module -Name "Verify.UpdateSummary" -ScriptBlock {
    param([Parameter(Mandatory = $true)] $SDK)
    $mod = @{ SDK = $SDK }
    . "$PSScriptRoot\..\..\..\..\book-0-builder\host-sdk\helpers\PowerShell.ps1"

    $mod.SDK.Testing.Verifications.Register("pkg-security", 17, [ordered]@{
        "Report generated" = {
            param($Worker)
            $Worker.Exec("sudo rm -f /var/lib/apt-notify/test-report.txt /var/lib/apt-notify/test-ai-summary.txt /var/lib/apt-notify/apt-notify.log") | Out-Null
            $queueLines = @("INSTALLED:testpkg:1.0.0", "UPGRADED:curl:7.81.0:7.82.0", "SNAP_UPGRADED:lxd:5.20:5.21",
                "BREW_UPGRADED:jq:1.6:1.7", "PIP_UPGRADED:requests:2.28.0:2.31.0", "NPM_UPGRADED:opencode:1.0.0:1.1.0", "DENO_UPGRADED:deno:1.40.0:1.41.0")
            $Worker.Exec("sudo rm -f /var/lib/apt-notify/apt-notify.queue") | Out-Null
            foreach ($line in $queueLines) { $Worker.Exec("sudo bash -c `"echo '$line' >> /var/lib/apt-notify/apt-notify.queue`"") | Out-Null }
            $Worker.Exec("sudo timeout 30 /usr/local/bin/apt-notify-flush") | Out-Null
            $reportExists = $Worker.Exec("sudo test -s /var/lib/apt-notify/test-report.txt && echo exists")
            $mod.SDK.Testing.Record(@{
                Test = "6.8.25"; Name = "Report generated"
                Pass = ($reportExists.Output -match "exists")
                Output = if ($reportExists.Output -match "exists") { "Report created" } else { "Report not created" }
            })
        }
        "Report contains npm section" = {
            param($Worker)
            $report = $Worker.Exec("cat /var/lib/apt-notify/test-report.txt 2>/dev/null").Output
            $hasNpm = ($report -match "NPM.*UPGRADED")
            $hasIsOdd = ($report -match "is-odd")
            $mod.SDK.Testing.Record(@{
                Test = "6.8.26"; Name = "Report contains npm section"
                Pass = ($hasNpm -and $hasIsOdd)
                Output = if ($hasNpm -and $hasIsOdd) { "NPM section with is-odd" } else { "Expected NPM section with is-odd" }
            })
        }
        "AI summary reports valid model" = {
            param($Worker)
            $settings = $mod.SDK.Settings
            $cliName = $null; $expectedModel = $null
            if ($settings.opencode -and $settings.opencode.enabled) {
                $cliName = "OpenCode"; $expectedModel = if ($settings.claude_code.model) { $settings.claude_code.model } else { "claude-haiku-4-5" }
            } elseif ($settings.claude_code -and $settings.claude_code.enabled) {
                $cliName = "Claude Code"; $expectedModel = if ($settings.claude_code.model) { $settings.claude_code.model } else { "claude-haiku-4-5" }
            } elseif ($settings.copilot_cli -and $settings.copilot_cli.enabled) {
                $cliName = "Copilot CLI"; $expectedModel = if ($settings.copilot_cli.model) { $settings.copilot_cli.model } else { "claude-haiku-4.5" }
            }
            if (-not $cliName) {
                $mod.SDK.Testing.Record(@{ Test = "6.8.27"; Name = "AI summary model"; Pass = $true; Output = "No AI CLI configured" }); return
            }
            $aiSummary = $Worker.Exec("cat /var/lib/apt-notify/test-ai-summary.txt 2>/dev/null").Output
            $cliMatch = ($aiSummary -match "Generated by $cliName")
            $modelPattern = "model: " + ($expectedModel -replace '[.\-]', '[.\-]')
            $mod.SDK.Testing.Record(@{
                Test = "6.8.27"; Name = "AI summary reports valid model"
                Pass = ($cliMatch -and ($aiSummary -match $modelPattern))
                Output = if ($cliMatch) { "CLI: $cliName, Model: $expectedModel" } else { "Expected $cliName with $expectedModel" }
            })
        }
    })
} -ArgumentList $SDK
